[package]
name = "migration"
version = "0.1.0"
edition = "2021"
publish = false

[lib]
name = "migration"
path = "src/lib.rs"

[dependencies]
sea-schema = { version = "0.5.1", default-features = false, features = [ "migration", "debug-print" ] }
entity = { path = "../entity/" }
chrono = "0.4.19"
