services:
  database:
    image: docker.io/mysql:8.0
    environment:
      MYSQL_DATABASE: iam
      MYSQL_USER: iam
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: secret
      TZ: Europe/Budapest
    ports:
        - "3306:3306"
