[package]
name = "entity"
version = "0.1.0"
edition = "2021"
license-file.workspace = true

[dependencies]
sea-orm = { version = "0.10.6", default-features = false, features = ["runtime-actix-rustls", "sqlx-mysql", "macros", "with-chrono"] }
