name: CI
on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: restore build & cargo cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: build
          args: --locked

  fmt:
    name: Format
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: rustfmt

      - uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: -- --check

  clippy:
    name: Clippy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          components: clippy

      - name: restore build & cargo cache
        uses: Swatinem/rust-cache@v1

      - uses: actions-rs/cargo@v1
        with:
          command: clippy
          args: --locked -- -D warnings

  test:
    name: Test
    runs-on: ubuntu-latest
    container: rust:alpine

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_DATABASE: iam
          MYSQL_ROOT_PASSWORD: secret
          TZ: Europe/Budapest
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      - uses: actions/checkout@v2
      - id: install
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: restore build & cargo cache
        uses: Swatinem/rust-cache@v1

      - name: Build
        uses: actions-rs/cargo@v1
        with:
          command: test
          args: -- --test-threads 1
        env:
          DB_USERNAME: root
          DB_PASSWORD: secret
          DB_HOST: mysql:3306
          DB_DATABASE: iam
